import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const companyId = "cmpmqnn1w0000chu0i1gtt9co";

const practices = [
  { practiceNumber: "8", practiceName: "Livingston" },
  { practiceNumber: "10", practiceName: "Bolton Horwich" },
  { practiceNumber: "21", practiceName: "Peterborough" },
  { practiceNumber: "25", practiceName: "Huddersfield" },
  { practiceNumber: "26", practiceName: "Fareham Park Gate" },
  { practiceNumber: "34", practiceName: "Exeter" },
  { practiceNumber: "35", practiceName: "Chelmsford" },
  { practiceNumber: "37", practiceName: "New Malden" },
  { practiceNumber: "41", practiceName: "Bournemouth" },
  { practiceNumber: "63", practiceName: "Kings Lynn" },
  { practiceNumber: "70", practiceName: "Christchurch" },
  { practiceNumber: "73", practiceName: "Redditch Trescott Road" },
  { practiceNumber: "78", practiceName: "Basildon" },
  { practiceNumber: "79", practiceName: "Leicester Fosse Park" },
  { practiceNumber: "83", practiceName: "Stratford" },
  { practiceNumber: "96", practiceName: "Slough" },
  { practiceNumber: "97", practiceName: "Kirkcaldy" },
  { practiceNumber: "101", practiceName: "Ayr" },
  { practiceNumber: "102", practiceName: "Bradford Idle (Eccleshill)" },
  { practiceNumber: "105", practiceName: "Bramley" },
  { practiceNumber: "117", practiceName: "Halifax" },
  { practiceNumber: "119", practiceName: "Stafford" },
  { practiceNumber: "125", practiceName: "Hull" },
  { practiceNumber: "127", practiceName: "Doncaster Wheatley" },
  { practiceNumber: "135", practiceName: "Gamston" },
  { practiceNumber: "136", practiceName: "Mapperley" },
  { practiceNumber: "138", practiceName: "Newport" },
  { practiceNumber: "140", practiceName: "South Shields" },
  { practiceNumber: "142", practiceName: "Stockton" },
  { practiceNumber: "143", practiceName: "Preston" },
  { practiceNumber: "149", practiceName: "Dudley" },
  { practiceNumber: "154", practiceName: "Bolton" },
  { practiceNumber: "160", practiceName: "Sheffield" },
  { practiceNumber: "162", practiceName: "Bitterne" },
  { practiceNumber: "167", practiceName: "Paisley" },
  { practiceNumber: "184", practiceName: "Rayleigh" },
  { practiceNumber: "185", practiceName: "Leigh-on-Sea" },
  { practiceNumber: "186", practiceName: "Rugby" },
  { practiceNumber: "192", practiceName: "Portsmouth" },
  { practiceNumber: "194", practiceName: "Kidderminster" },
  { practiceNumber: "197", practiceName: "Cardiff Llanrumney" },
  { practiceNumber: "198", practiceName: "Grantham" },
  { practiceNumber: "200", practiceName: "Worksop" },
  { practiceNumber: "201", practiceName: "Walton Vale" },
  { practiceNumber: "204", practiceName: "Beverley" },
  { practiceNumber: "207", practiceName: "Castleford" },
  { practiceNumber: "211", practiceName: "Washington" },
  { practiceNumber: "214", practiceName: "York" },
  { practiceNumber: "218", practiceName: "Bishop Auckland" },
  { practiceNumber: "255", practiceName: "Speke" },
  { practiceNumber: "268", practiceName: "Stocksbridge" },
  { practiceNumber: "270", practiceName: "Derby Kingsway" },
  { practiceNumber: "274", practiceName: "Leighton Buzzard" },
  { practiceNumber: "276", practiceName: "Wrexham Plas Coch" },
  { practiceNumber: "281", practiceName: "Bedford" },
  { practiceNumber: "283", practiceName: "Corstorphine" },
  { practiceNumber: "286", practiceName: "Barnsley Cortonwood" },
  { practiceNumber: "288", practiceName: "Bletchley" },
  { practiceNumber: "295", practiceName: "Preston Capitol" },
  { practiceNumber: "302", practiceName: "Rotherham Parkgate" },
  { practiceNumber: "305", practiceName: "Dorchester" },
  { practiceNumber: "309", practiceName: "Sheffield Wadsley Bridge" },
  { practiceNumber: "314", practiceName: "Prescot" },
  { practiceNumber: "326", practiceName: "Bangor NW" },
  { practiceNumber: "336", practiceName: "Newtownabbey" },
  { practiceNumber: "337", practiceName: "Torquay" },
  { practiceNumber: "344", practiceName: "York Clifton Moor" },
  { practiceNumber: "349", practiceName: "Hull Anlaby" },
  { practiceNumber: "350", practiceName: "Yeovil" },
  { practiceNumber: "354", practiceName: "Greasby" },
  { practiceNumber: "360", practiceName: "Oxford Cowley" },
  { practiceNumber: "369", practiceName: "Wallasey (Bidston Moss)" },
  { practiceNumber: "372", practiceName: "Maidenhead" },
  { practiceNumber: "376", practiceName: "Barry" },
  { practiceNumber: "380", practiceName: "Accrington" },
  { practiceNumber: "381", practiceName: "Dewsbury" },
  { practiceNumber: "389", practiceName: "Drumchapel" },
  { practiceNumber: "398", practiceName: "Cardiff Ely" },
  { practiceNumber: "401", practiceName: "Catterick Garrison" },
  { practiceNumber: "405", practiceName: "Bishop's Stortford" },
  { practiceNumber: "410", practiceName: "Stourbridge" },
  { practiceNumber: "428", practiceName: "Swindon Bridgemead" },
  { practiceNumber: "433", practiceName: "Worthing" },
  { practiceNumber: "439", practiceName: "Prestwich" },
  { practiceNumber: "440", practiceName: "Newmarket" },
  { practiceNumber: "445", practiceName: "Chilwell" },
  { practiceNumber: "449", practiceName: "Bath" },
  { practiceNumber: "453", practiceName: "Newtownards" },
  { practiceNumber: "459", practiceName: "Leeds Kirkstall" },
  { practiceNumber: "463", practiceName: "Southport" },
  { practiceNumber: "471", practiceName: "Hamilton" },
  { practiceNumber: "475", practiceName: "Irvine" },
  { practiceNumber: "477", practiceName: "Burton" },
  { practiceNumber: "483", practiceName: "Nuneaton" },
  { practiceNumber: "489", practiceName: "Leeds Colton" },
  { practiceNumber: "497", practiceName: "Northwich" },
  { practiceNumber: "503", practiceName: "Telford Madeley" },
  { practiceNumber: "505", practiceName: "Leigh" },
  { practiceNumber: "514", practiceName: "East Kilbride" },
  { practiceNumber: "515", practiceName: "Hucknall" },
  { practiceNumber: "548", practiceName: "Glasgow Pollokshaws" },
  { practiceNumber: "553", practiceName: "Coalville" },
  { practiceNumber: "571", practiceName: "Brighton" },
  { practiceNumber: "573", practiceName: "Staines" },
  { practiceNumber: "587", practiceName: "Whetstone" },
  { practiceNumber: "594", practiceName: "Isle of Man" },
  { practiceNumber: "744", practiceName: "Bromborough" },
  { practiceNumber: "600", practiceName: "Bodmin" },
  { practiceNumber: "762", practiceName: "Newark" },
];

async function main() {
  for (const p of practices) {
    await prisma.practice.upsert({
      where: {
        practiceNumber_companyId: {
          practiceNumber: p.practiceNumber,
          companyId,
        },
      },
      update: {
        practiceName: p.practiceName,
      },
      create: {
        practiceNumber: p.practiceNumber,
        practiceName: p.practiceName,
        companyId,
      },
    });
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
