name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the backend
      - name: Build
        run: npm run build

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/virtual-water-backend

            # <<< ADDED: Force reset local changes to match GitHub
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies fresh
            npm ci

            # Build the backend
            npm run build

            # Restart with PM2 or start if not running
            pm2 restart virtualwater || pm2 start "dotenv -e .env -- node dist/src/index.js" --name virtualwater
